name: Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y gcc make build-essential libmnl-dev busybox-static libcurl4-openssl-dev

    - name: Build project
      run: make -C ${{ github.workspace }}
